/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *vbox1;
  GtkWidget *toolbar1;
  GtkIconSize tmp_toolbar_icon_size;
  GSList *toolbutton_en_pl_group = NULL;
  GtkWidget *tmp_image;
  GtkWidget *toolbutton_en_pl;
  GtkWidget *toolbutton_pl_en;
  GtkWidget *toolbutton_de_pl;
  GtkWidget *toolbutton_pl_de;
  GtkWidget *separatortoolitem1;
  GtkWidget *toolbutton_copy;
  GtkWidget *hpaned1;
  GtkWidget *vbox2;
  GtkWidget *entry1;
  GtkWidget *scrolledwindow2;
  GtkWidget *treeview1;
  GtkWidget *scrolledwindow1;
  GtkWidget *viewport1;
  GtkWidget *gtkhtml1;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("YDP Dictionary"));
  gtk_window_set_default_size (GTK_WINDOW (window1), 640, 480);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (window1), vbox1);

  toolbar1 = gtk_toolbar_new ();
  gtk_widget_show (toolbar1);
  gtk_box_pack_start (GTK_BOX (vbox1), toolbar1, FALSE, FALSE, 0);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar1), GTK_TOOLBAR_ICONS);
  tmp_toolbar_icon_size = gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar1));

  toolbutton_en_pl = (GtkWidget*) gtk_radio_tool_button_new (NULL);
  gtk_tool_button_set_label (GTK_TOOL_BUTTON (toolbutton_en_pl), _("English-Polish"));
  tmp_image = create_pixmap (window1, "enpl.png");
  gtk_widget_show (tmp_image);
  gtk_tool_button_set_icon_widget (GTK_TOOL_BUTTON (toolbutton_en_pl), tmp_image);
  gtk_widget_show (toolbutton_en_pl);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolbutton_en_pl);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (toolbutton_en_pl), tooltips, _("Switch to English-Polish Dictionary"), NULL);
  gtk_radio_tool_button_set_group (GTK_RADIO_TOOL_BUTTON (toolbutton_en_pl), toolbutton_en_pl_group);
  toolbutton_en_pl_group = gtk_radio_tool_button_get_group (GTK_RADIO_TOOL_BUTTON (toolbutton_en_pl));

  toolbutton_pl_en = (GtkWidget*) gtk_radio_tool_button_new (NULL);
  gtk_tool_button_set_label (GTK_TOOL_BUTTON (toolbutton_pl_en), "");
  tmp_image = create_pixmap (window1, "plen.png");
  gtk_widget_show (tmp_image);
  gtk_tool_button_set_icon_widget (GTK_TOOL_BUTTON (toolbutton_pl_en), tmp_image);
  gtk_widget_show (toolbutton_pl_en);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolbutton_pl_en);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (toolbutton_pl_en), tooltips, _("Switch to Polish-English dictionary"), NULL);
  gtk_radio_tool_button_set_group (GTK_RADIO_TOOL_BUTTON (toolbutton_pl_en), toolbutton_en_pl_group);
  toolbutton_en_pl_group = gtk_radio_tool_button_get_group (GTK_RADIO_TOOL_BUTTON (toolbutton_pl_en));

  toolbutton_de_pl = (GtkWidget*) gtk_radio_tool_button_new (NULL);
  gtk_tool_button_set_label (GTK_TOOL_BUTTON (toolbutton_de_pl), "");
  tmp_image = create_pixmap (window1, "depl.png");
  gtk_widget_show (tmp_image);
  gtk_tool_button_set_icon_widget (GTK_TOOL_BUTTON (toolbutton_de_pl), tmp_image);
  gtk_widget_show (toolbutton_de_pl);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolbutton_de_pl);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (toolbutton_de_pl), tooltips, _("Switch to German-Polish dictionary"), NULL);
  gtk_radio_tool_button_set_group (GTK_RADIO_TOOL_BUTTON (toolbutton_de_pl), toolbutton_en_pl_group);
  toolbutton_en_pl_group = gtk_radio_tool_button_get_group (GTK_RADIO_TOOL_BUTTON (toolbutton_de_pl));

  toolbutton_pl_de = (GtkWidget*) gtk_radio_tool_button_new (NULL);
  gtk_tool_button_set_label (GTK_TOOL_BUTTON (toolbutton_pl_de), "");
  tmp_image = create_pixmap (window1, "plde.png");
  gtk_widget_show (tmp_image);
  gtk_tool_button_set_icon_widget (GTK_TOOL_BUTTON (toolbutton_pl_de), tmp_image);
  gtk_widget_show (toolbutton_pl_de);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolbutton_pl_de);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (toolbutton_pl_de), tooltips, _("Switch to Polish-German dictionary"), NULL);
  gtk_radio_tool_button_set_group (GTK_RADIO_TOOL_BUTTON (toolbutton_pl_de), toolbutton_en_pl_group);
  toolbutton_en_pl_group = gtk_radio_tool_button_get_group (GTK_RADIO_TOOL_BUTTON (toolbutton_pl_de));

  separatortoolitem1 = (GtkWidget*) gtk_separator_tool_item_new ();
  gtk_widget_show (separatortoolitem1);
  gtk_container_add (GTK_CONTAINER (toolbar1), separatortoolitem1);

  toolbutton_copy = (GtkWidget*) gtk_tool_button_new_from_stock ("gtk-copy");
  gtk_widget_show (toolbutton_copy);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolbutton_copy);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (toolbutton_copy), tooltips, _("Copy word definition"), NULL);

  hpaned1 = gtk_hpaned_new ();
  gtk_widget_show (hpaned1);
  gtk_box_pack_start (GTK_BOX (vbox1), hpaned1, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hpaned1), 4);

  vbox2 = gtk_vbox_new (FALSE, 5);
  gtk_widget_show (vbox2);
  gtk_paned_pack1 (GTK_PANED (hpaned1), vbox2, FALSE, TRUE);
  gtk_widget_set_size_request (vbox2, 160, -1);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_box_pack_start (GTK_BOX (vbox2), entry1, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, entry1, _("Enter word"), NULL);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow2);
  gtk_box_pack_start (GTK_BOX (vbox2), scrolledwindow2, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_POLICY_NEVER, GTK_POLICY_ALWAYS);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_SHADOW_IN);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), treeview1);
  gtk_tooltips_set_tip (tooltips, treeview1, _("Select word"), NULL);
  gtk_tree_view_set_headers_visible (GTK_TREE_VIEW (treeview1), FALSE);
  gtk_tree_view_set_enable_search (GTK_TREE_VIEW (treeview1), FALSE);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_paned_pack2 (GTK_PANED (hpaned1), scrolledwindow1, TRUE, TRUE);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_NEVER, GTK_POLICY_ALWAYS);

  viewport1 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), viewport1);

  gtkhtml1 = create_gtkhtml1 ("gtkhtml1", "", "", 0, 0);
  gtk_widget_show (gtkhtml1);
  gtk_container_add (GTK_CONTAINER (viewport1), gtkhtml1);
  GTK_WIDGET_UNSET_FLAGS (gtkhtml1, GTK_CAN_FOCUS);
  GTK_WIDGET_UNSET_FLAGS (gtkhtml1, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) window1, "destroy",
                    G_CALLBACK (on_window1_destroy),
                    NULL);
  g_signal_connect ((gpointer) toolbutton_en_pl, "toggled",
                    G_CALLBACK (on_toolbutton_en_pl_toggled),
                    NULL);
  g_signal_connect ((gpointer) toolbutton_pl_en, "toggled",
                    G_CALLBACK (on_toolbutton_pl_en_toggled),
                    NULL);
  g_signal_connect ((gpointer) toolbutton_de_pl, "toggled",
                    G_CALLBACK (on_toolbutton_de_pl_toggled),
                    NULL);
  g_signal_connect ((gpointer) toolbutton_pl_de, "toggled",
                    G_CALLBACK (on_toolbutton_pl_de_toggled),
                    NULL);
  g_signal_connect ((gpointer) toolbutton_copy, "clicked",
                    G_CALLBACK (on_toolbutton_copy_clicked),
                    NULL);
  g_signal_connect ((gpointer) entry1, "changed",
                    G_CALLBACK (on_entry1_changed),
                    NULL);
  g_signal_connect ((gpointer) entry1, "key_press_event",
                    G_CALLBACK (on_entry1_key_press_event),
                    NULL);
  g_signal_connect ((gpointer) treeview1, "cursor_changed",
                    G_CALLBACK (on_treeview1_cursor_changed),
                    NULL);
  g_signal_connect ((gpointer) treeview1, "key_press_event",
                    G_CALLBACK (on_treeview1_key_press_event),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (window1, toolbar1, "toolbar1");
  GLADE_HOOKUP_OBJECT (window1, toolbutton_en_pl, "toolbutton_en_pl");
  GLADE_HOOKUP_OBJECT (window1, toolbutton_pl_en, "toolbutton_pl_en");
  GLADE_HOOKUP_OBJECT (window1, toolbutton_de_pl, "toolbutton_de_pl");
  GLADE_HOOKUP_OBJECT (window1, toolbutton_pl_de, "toolbutton_pl_de");
  GLADE_HOOKUP_OBJECT (window1, separatortoolitem1, "separatortoolitem1");
  GLADE_HOOKUP_OBJECT (window1, toolbutton_copy, "toolbutton_copy");
  GLADE_HOOKUP_OBJECT (window1, hpaned1, "hpaned1");
  GLADE_HOOKUP_OBJECT (window1, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (window1, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (window1, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (window1, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (window1, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (window1, viewport1, "viewport1");
  GLADE_HOOKUP_OBJECT (window1, gtkhtml1, "gtkhtml1");
  GLADE_HOOKUP_OBJECT_NO_REF (window1, tooltips, "tooltips");

  gtk_widget_grab_focus (entry1);
  return window1;
}

GtkWidget*
create_window2 (void)
{
  GtkWidget *window2;
  GtkWidget *vbox3;
  GtkWidget *label1;
  GtkWidget *progressbar1;

  window2 = gtk_window_new (GTK_WINDOW_POPUP);
  gtk_widget_set_size_request (window2, 320, -1);
  gtk_container_set_border_width (GTK_CONTAINER (window2), 10);
  gtk_window_set_title (GTK_WINDOW (window2), _("window2"));
  gtk_window_set_position (GTK_WINDOW (window2), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (window2), TRUE);
  gtk_window_set_type_hint (GTK_WINDOW (window2), GDK_WINDOW_TYPE_HINT_TOOLBAR);

  vbox3 = gtk_vbox_new (FALSE, 4);
  gtk_widget_show (vbox3);
  gtk_container_add (GTK_CONTAINER (window2), vbox3);

  label1 = gtk_label_new (_("<i>Loading dictionary...</i>"));
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (vbox3), label1, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label1), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label1), 0, 0.5);

  progressbar1 = gtk_progress_bar_new ();
  gtk_widget_show (progressbar1);
  gtk_box_pack_start (GTK_BOX (vbox3), progressbar1, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window2, window2, "window2");
  GLADE_HOOKUP_OBJECT (window2, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (window2, label1, "label1");
  GLADE_HOOKUP_OBJECT (window2, progressbar1, "progressbar1");

  return window2;
}

