/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>
#include <ydpdict/ydpdict.h>

#include "interface.h"
#include "support.h"
#include "dictionary.h"

int
main (int argc, char *argv[])
{
  GtkWidget *window1;
  ydpdict_t *dict;
  gboolean debug = FALSE;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();

  g_thread_init (NULL);
  gdk_threads_init ();
  gdk_threads_enter ();

  gtk_init (&argc, &argv);

  { int i; printf("argc=%d", argc); for (i = 0; i < argc; i++) printf(", argv[%d]=\"%s\"", i, argv[i]); }

  // XXX dodać prawdziwe getopt()
  if (argc > 1 && strcmp(argv[1], "--debug") == 0)
    debug = 1;

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");
  add_pixmap_directory ("../pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  window1 = create_window1 ();

  if (debug) {
    GtkWidget *tmp;

    tmp = lookup_widget(window1, "toolbutton_test");
    gtk_widget_show(tmp);

    tmp = lookup_widget(window1, "separatortoolitem_format");
    gtk_widget_show(tmp);

    tmp = lookup_widget(window1, "combobox_format");
    gtk_combo_box_set_active(GTK_COMBO_BOX(tmp), FORMAT_ALL);
    gtk_widget_show(tmp);
  }

  gtk_widget_show (window1);

  treeview1_init (window1);

  switch_dictionary(window1, YDPDICT_EN_PL);

  gtk_main ();

  gdk_threads_leave ();

  return 0;
}

